### ISSUE TITLE
04_UART example rebooting every ~50 seconds

### ISSUE THREAD

**Issue by HumbertoOntiveros** [allexoll/BBB-BareMetal#3]
Hello, guys! I hope you're doing great.

I've been playing with the "04_UART" example in this repository, and I found out that the BBB reboots approximately every 50 seconds. It's kind of annoying having the BBB rebooting every 50 seconds, and I would like to fix this behavior. I've been searching on the internet, and I think it's something related to the WDT(https://stackoverflow.com/questions/30803100/watchdog-timer-in-beaglebone-black), but I haven't succeeded in my tries to fix this problem. So, I would like to know if you have had the same problem and if you know how to fix this behavior.

Thanks in advance.

HuOn

**Comment by allexoll** [comment]
it's very likely related to the WDT indeed. if you look at the PDF linked on that stackoverflow question, and go to section 20.4 for the watchdog timer, you can find information on how to stop it in section 20.4.3.8 .

I'm sure I had the same problem, but that was 9 years ago...

**Comment by HumbertoOntiveros** [comment]
Hi @allexoll,

Thank you so much for the guidance. I've resolved the problem based on section 20.4.3.8 as you mentioned. Now the BBB is not rebooting every ~50 anymore. I can prepare a pull request to fix this behavior in the 04_UART example. Let me know if you consider this would be helpful.

Best regards,

HuOn

**Comment by allexoll** [comment]
if you want, sure! I don't intend to work on this repository myself, this was more of a logbook for me back then, so you decide if you want to go trough, i'll gladly merge it. on a side note, I suppose that this watchdog reset issue is present in all projects, not only in the UART one, so even just a note on the readme might be enough if you want

**Comment by HumbertoOntiveros** [comment]
Hi @allexoll,

I've just added the PR to solve this issue: #4.

Thank you so much for the guidance.
HuOn
